### PR TITLE
Fix XR occlusion mesh shader compilation error with GLES2

### PR DESCRIPTION
**Pull request by fabien-unity**
---
### Purpose of this PR
Fix shader compilation error introduced by https://github.com/Unity-Technologies/Graphics/pull/1349 and reported in https://fogbugz.unity3d.com/f/cases/1279514/

---
### Testing status

**Manual Tests**: I used the repro steps mentioned in the ticket

**Yamato**: [running](https://yamato.cds.internal.unity3d.com/jobs/902-Graphics/tree/universal%252Fxr%252Ffix-gles2-occlusion-mesh/.yamato%252F_abv.yml%2523all_project_ci_trunk)

### CODE REVIEW

**Comment by thomas-zeng** [comment]
Do we consider strip occlusion pass shaders when targeting GLES2? Similar to this commit: https://github.com/Unity-Technologies/Graphics/pull/1392/commits/16088b40482ed07aef77f782f621fa8da374b018
URP XR requires at least GLES3 to work anyway.

**Review by thomas-zeng — COMMENTED** [review]
Do we consider strip occlusion pass shaders when targeting GLES2? Similar to this commit: 16088b4
URP XR requires at least GLES3 to work anyway.

**Comment by phi-lira** [comment]
@kaychang-unity seems to have also worked on a similar fix in this PR: https://github.com/Unity-Technologies/Graphics/pull/1964

**Review by phi-lira — APPROVED** [review]

**Review by erikabar — APPROVED** [review]
Verified case 1279514, did a smoke test with URP template

**Review by thomas-zeng — APPROVED** [review]

**Comment by fabien-unity** [comment]
I'm closing this PR as the code was integrated into https://github.com/Unity-Technologies/Graphics/pull/1964 which fixes all the GLES2 reported issues at once.
