### PR TITLE
[VFX] Fix compilation error when shaderGraph is modified

### PR DESCRIPTION
**Pull request by PaulDemeulenaere**
---
### Purpose of this PR
Fix case https://fogbugz.unity3d.com/f/cases/1361601/

The regression has been introduced by https://github.com/Unity-Technologies/Graphics/pull/4971 & https://github.com/Unity-Technologies/Graphics/pull/5104 but it can't be tested prior this change, the last C++ producing the correct old behavior is 21.2a21.

**0)** What was happening before "Fix Sanitize" https://github.com/Unity-Technologies/Graphics/pull/4971 :
_1st VFX import_
- Preprocess: 
    - Sanitize applied, PrepareSubgraph called, **CheckGraphBeforeImport** processed, graph marked as sanitize
    - VFX Graph Compilation is executed 🟢
- PostProcess: Nothing

_The dependent shaderGraph is modified_
- Preprocess: 
    - Sanitize is skipped (because already sanitize), **CheckGraphBeforeImport** processed, PrepareSubgraph called.
    - VFX Graph Compilation is executed 🟢
- PostProcess : Nothing

**1)** After "Fix Sanitize" https://github.com/Unity-Technologies/Graphics/pull/4971
_1st VFX import_
- Preprocess called:
    - Everything is skipped because not sanitized 🟠
- PostProcess: 
    - Sanitize applied, PrepareSubgraph called, **CheckGraphBeforeImport** processed, graph marked as sanitize
    - Reimport is triggered
- Preprocess called:
    -  PrepareSubgraph is called (which was problematic ⏳) 
    - VFX Graph Compilation is executed 🟢 
- PostProcess: **CheckGraphBeforeImport**

_The dependent shaderGraph is modified_
- Preprocess called:
    - Because the graph is already marked as sanitize, continue
    - PrepareSubgraph is called (still problematic)
    - VFX Graph Compilation is executed 🟢
- PostProcess: **CheckGraphBeforeImport**

**2)** After "Fix Subgraph" https://github.com/Unity-Technologies/Graphics/pull/5104
Same than **1)** but the PrepareSubgraph changes are now safely handled preventing any deleted references serialized in graph.
- ...
- Preprocess called:
    - VFX is backuped
    -  PrepareSubgraph is called (which is no more an issue thanks to previous backup)
    - VFX Graph Compilation is executed 🟢 
    - VFX is restored
-...

**The problem !**
After first import the graph is marked as sanitized but the CheckGraphBeforeImport is occurring too late:
(...)
_The dependent shaderGraph is modified_
- Preprocess called:
    - Because the graph is already marked as sanitize, continue
    - PrepareSubgraph is called
    - VFX Graph Compilation is executed => 🔴 It fails because this [ResyncSlot](https://github.com/Unity-Technologies/Graphics/blob/master/com.unity.visualeffectgraph/Editor/ShaderGraph/VFXShaderGraphParticleOutput.cs#L396) is only called afterwards
- PostProcess: **CheckGraphBeforeImport**

**3)** After this fix (and more precisely https://github.com/Unity-Technologies/Graphics/commit/f62f1b672d635a221abb96636ecd38ca52c49df6) adding CheckGraphBeforeImport process before compilation
- ...
- Preprocess called:
    - VFX is backuped
    - PrepareSubgraph is called
    - **CheckGraphBeforeImport** ◀️Fix 🔧 
    - VFX Graph Compilation is executed 🟢 
    - VFX is restored
- PostProcess: **CheckGraphBeforeImport** (still needed because the previous one has been reverted)

N.B.: As PrepareSubgraph, the CheckGraphBeforeImport is safe during preprocess only because we are backuping/restoring the graph, otherwise, slot created during preprocess will be destroyed after the import.

---
### Testing status
Tested locally with described repro step.

Tested manually at this revision (other integration branch) : https://github.com/Unity-Technologies/Graphics/pull/5448/commits/61ebca16d50e3eec30164e9520d4a68ea02a584b
_fix_in_urp_integration

Added an editor regression test `Modify_ShaderGraph_Property_Check_VFX_Compilation_Doesnt_Fail` 
It simulates the repro step modifying the shaderGraph content.

**Before**
image

**After**
image

Run all test locally
image

Yamato trunk 🟢 
Yamato 2021.2 at [cba0eba12ed723121f116ca85995475593fe3963 ](https://ono.unity3d.com/unity/unity/changeset/cba0eba12ed723121f116ca85995475593fe3963) 🟢 

---
### Comments to reviewers
We are planning a live code review on this change with @julienf-unity 

N.B: We could also benefit from the rework of OnPostprocessAllAssets thanks to [this PR](https://ono.unity3d.com/unity/unity/pull-request/128606/_/assetpipeline/postprocessallassets-in-asset-db-ready-state) but these changes hasn't landed in 21.2 (see this [conversation](https://unity.slack.com/archives/C0QSF3JES/p1628609807120700?thread_ts=1627890340.024600&cid=C0QSF3JES))

### CODE REVIEW

**Comment by VitaSkruibyte** [comment]
Thanks for the fix Paul! Quick summary - specifically  `Vector 3` issue seems to be fixed, but this bug is still lurking behind the corner (it happens with other properties under certain circumstances).

Here's the work in progress [test doc](https://docs.google.com/document/d/1Y9hPraKvRb3FR-e2IEcR152n-WVU4NlLAxkFYJ6vz2s/edit?usp=sharing), logged all the scenarios I managed to find about this main issue, also logged some not caused by the PR bugs, maybe something will draw your attention and could be fixed.

**Review by julienf-unity — APPROVED** [review]

**Comment by VitaSkruibyte** [comment]
Thanks for the fix! 

Error is no longer persistent. Tried:
- Various setups while testing SG integration to URP
- Existing URP/HDRP projects
- New URP/HDRP projects
- Most of the properties created from inline nodes and through blackboard
- Tried connecting all the vertex/fragment ports
- Reimporting VFX/SG


Other issues raised in test doc are unrelated to PR.

**Review by VitaSkruibyte — APPROVED** [review]

**Comment by PaulDemeulenaere** [comment]
I double checked the changelog.md, expected job are green 🟢 at this revision f6d7f031b8a4d39bb7487d35738e33640d611bb0
Ready to be merged
