### PR TITLE
[VFX] Fix compilation error when using cubemap arrays

### PR DESCRIPTION
**Pull request by julienf-unity**
### Purpose of this PR
This fixes an issue introduced by https://github.com/Unity-Technologies/Graphics/pull/5149
Edit mode tests are currently failing on master because of that.

Typically using cubemap array in a graph (in a compute pass) currently ends up with a compile error, even on platforms supporting it.
This is fixed by this PR.

This is a temp workaround, I created a fogbugz as well for Shader System team to fix it properly https://fogbugz.unity3d.com/f/cases/1364139/

---
### Testing status
Tested locally that all VFX tests pass

---
### Comments to reviewers
Notes for the reviewers you have assigned.

### CODE REVIEW

**Review by VladNeykov — APPROVED** [review]
Developer-tested, not much for QA to do beside re-run the same tests.
Auto-approving.

**Review by PaulDemeulenaere — APPROVED** [review]
The workaround looks good to me, we should double check the status of this Yamato job : https://unity-ci.cds.internal.unity3d.com/job/8630091 (VFX_HDRP in edit mode)

**Comment by PaulDemeulenaere** [comment]
*Update*
We got an issue in HDRP Edit Mode:
```
[12:48:46.351 Information] [496/1143] TestFinish
	name: UnityEditor.VFX.Test.VisualEffectTest.CreateComponent_Modify_Value_Doesnt_Reset(False,True)
	result: FAILED
	message: Unhandled log message: '[Exception] ArgumentException: Getting control 9's position in a group with only 9
[12:48:46.355 Information]  controls when doing repaint
```
Definitely not related to your change, I'm looking for the root cause ⏳ 
Feel free to merge.
